# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spotpilot < Formula
  desc "Control Spotify from the command line — built for AI agents"
  homepage "https://github.com/ignatij/spotpilot"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ignatij/spotpilot/releases/download/v0.1.3/spotpilot_darwin_amd64.tar.gz"
      sha256 "a7373307a6f1943e6b10b0577a7a845ffbd19445af40527938d32f4c13efd4bd"

      define_method(:install) do
        bin.install "spotpilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ignatij/spotpilot/releases/download/v0.1.3/spotpilot_darwin_arm64.tar.gz"
      sha256 "ac46f136b6266d3e6dd0b658fd1f26b9cd30fba4dbac74b2b9e16ea9b54fe80f"

      define_method(:install) do
        bin.install "spotpilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignatij/spotpilot/releases/download/v0.1.3/spotpilot_linux_amd64.tar.gz"
      sha256 "c911b3ce405760a24d1ddfe5606f872b8e87a714d203c6ef33ea8c8b48620961"
      define_method(:install) do
        bin.install "spotpilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignatij/spotpilot/releases/download/v0.1.3/spotpilot_linux_arm64.tar.gz"
      sha256 "4bb59c2d86032b908c906741c64ee65dc6ee5a5f22d59c6435a21f7b4286f5d0"
      define_method(:install) do
        bin.install "spotpilot"
      end
    end
  end

  test do
    system "#{bin}/spotpilot", "version"
  end
end
