# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spotpilot < Formula
  desc "Control Spotify from the command line — built for AI agents"
  homepage "https://github.com/ignatij/spotpilot"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ignatij/spotpilot/releases/download/v0.1.0/spotpilot_darwin_amd64.tar.gz"
      sha256 "4431ef3562def50e01739fe4250aa5a5c679c425bdf84c818a689c9207b020c8"

      define_method(:install) do
        bin.install "spotpilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ignatij/spotpilot/releases/download/v0.1.0/spotpilot_darwin_arm64.tar.gz"
      sha256 "3e53abdd3683c41601577184158d6e9ca311fbd43314be54561ba983f909aa1d"

      define_method(:install) do
        bin.install "spotpilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignatij/spotpilot/releases/download/v0.1.0/spotpilot_linux_amd64.tar.gz"
      sha256 "4879cd6fabc537001da2738006eb3742d00dc464bc27a2fb9d9397961f277d63"
      define_method(:install) do
        bin.install "spotpilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ignatij/spotpilot/releases/download/v0.1.0/spotpilot_linux_arm64.tar.gz"
      sha256 "85808ad3d88f0def0269e8315c7e3350172c6930676d3114909e8d311b1ba290"
      define_method(:install) do
        bin.install "spotpilot"
      end
    end
  end

  test do
    system "#{bin}/spotpilot", "version"
  end
end
